import { HeroUIProvider } from "@heroui/system"
import type { Metadata } from "next"
import { NextIntlClientProvider } from "next-intl"
import { getLocale } from "next-intl/server"
import { Geist, Geist_Mono } from "next/font/google"
import { Toaster } from "sonner"

import TanstackProvider from "@/providers/TanstackProvider"
import { ThemeProvider } from "@/providers/ThemeProvider"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TanstackProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NextIntlClientProvider>
              <HeroUIProvider>
                {children}
                <Toaster position="bottom-right" richColors />
              </HeroUIProvider>
            </NextIntlClientProvider>
          </ThemeProvider>
        </TanstackProvider>
      </body>
    </html>
  )
}
